name: Lint

on:
  pull_request:

  workflow_dispatch:

jobs:
  lint:
    name: Check - Lint

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install
        run: npm install

      - name: Lint check
        run: npm run lint -- --max-warnings 0
